# Generated by Django 4.1 on 2022-09-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
